'use client';

import { useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, ChevronLeft, ChevronRight } from 'lucide-react';

interface LightboxProps {
  images: Array<{ url: string; modelName: string }>;
  currentIndex: number;
  isOpen: boolean;
  onClose: () => void;
  onNext: () => void;
  onPrev: () => void;
  onGoToIndex?: (index: number) => void;
}

export default function Lightbox({
  images,
  currentIndex,
  isOpen,
  onClose,
  onNext,
  onPrev,
  onGoToIndex,
}: LightboxProps) {
  // Bounds-check the index to prevent out-of-range access
  const safeIndex = images.length > 0 ? Math.min(currentIndex, images.length - 1) : 0;
  const currentImage = images[safeIndex];
  const hasMultipleImages = images.length > 1;

  // Keyboard navigation
  const handleKeyDown = useCallback(
    (e: KeyboardEvent) => {
      if (!isOpen) return;

      switch (e.key) {
        case 'Escape':
          onClose();
          break;
        case 'ArrowLeft':
          if (hasMultipleImages) onPrev();
          break;
        case 'ArrowRight':
          if (hasMultipleImages) onNext();
          break;
      }
    },
    [isOpen, onClose, onNext, onPrev, hasMultipleImages]
  );

  useEffect(() => {
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [handleKeyDown]);

  // Prevent body scroll when lightbox is open
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [isOpen]);

  return (
    <AnimatePresence>
      {isOpen && currentImage && (
        <motion.div
          role="dialog"
          aria-modal="true"
          aria-label="Image lightbox"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[100] flex items-center justify-center"
          onClick={onClose}
        >
          {/* Dark overlay background */}
          <div className="absolute inset-0 bg-black/90 backdrop-blur-sm" />

          {/* Close button */}
          <button
            onClick={(e) => {
              e.stopPropagation();
              onClose();
            }}
            className="absolute top-4 right-4 z-10 p-2 rounded-full bg-white/10 hover:bg-white/20 transition-colors group"
            aria-label="Close lightbox"
          >
            <X className="w-6 h-6 text-white group-hover:text-arcade-pink transition-colors" />
          </button>

          {/* Previous arrow */}
          {hasMultipleImages && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                onPrev();
              }}
              className="absolute left-4 top-1/2 -translate-y-1/2 z-10 p-3 rounded-full bg-white/10 hover:bg-white/20 transition-colors group"
              aria-label="Previous image"
            >
              <ChevronLeft className="w-8 h-8 text-white group-hover:text-arcade-cyan transition-colors" />
            </button>
          )}

          {/* Next arrow */}
          {hasMultipleImages && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                onNext();
              }}
              className="absolute right-4 top-1/2 -translate-y-1/2 z-10 p-3 rounded-full bg-white/10 hover:bg-white/20 transition-colors group"
              aria-label="Next image"
            >
              <ChevronRight className="w-8 h-8 text-white group-hover:text-arcade-cyan transition-colors" />
            </button>
          )}

          {/* Image container */}
          <motion.div
            key={safeIndex}
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.9 }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
            className="relative z-10 flex flex-col items-center max-w-[90vw] max-h-[90vh]"
            onClick={(e) => e.stopPropagation()}
          >
            {/* The image */}
            <img
              src={currentImage.url}
              alt={`Generated by ${currentImage.modelName}`}
              className="max-w-full max-h-[80vh] object-contain rounded-lg shadow-2xl"
            />

            {/* Model name below image */}
            <div className="mt-4 px-4 py-2 rounded-lg bg-arcade-dark/80 border border-arcade-purple/30">
              <span className="text-arcade-cyan font-medium">
                {currentImage.modelName}
              </span>
              {hasMultipleImages && (
                <span className="text-gray-400 ml-3 text-sm">
                  {safeIndex + 1} / {images.length}
                </span>
              )}
            </div>
          </motion.div>

          {/* Image indicators (dots) for multiple images */}
          {hasMultipleImages && (
            <div className="absolute bottom-6 left-1/2 -translate-x-1/2 z-10 flex gap-2">
              {images.map((_, idx) => (
                <button
                  key={idx}
                  onClick={(e) => {
                    e.stopPropagation();
                    // Navigate to specific index
                    if (onGoToIndex) {
                      onGoToIndex(idx);
                    } else {
                      // Fallback: use next/prev (less efficient but works)
                      const diff = idx - safeIndex;
                      if (diff > 0) {
                        for (let i = 0; i < diff; i++) onNext();
                      } else if (diff < 0) {
                        for (let i = 0; i < Math.abs(diff); i++) onPrev();
                      }
                    }
                  }}
                  className={`w-2 h-2 rounded-full transition-all ${
                    idx === safeIndex
                      ? 'bg-arcade-cyan w-6'
                      : 'bg-white/30 hover:bg-white/50'
                  }`}
                  aria-label={`Go to image ${idx + 1}`}
                />
              ))}
            </div>
          )}
        </motion.div>
      )}
    </AnimatePresence>
  );
}
