import { NextRequest, NextResponse } from 'next/server';

const VENICE_API_BASE = 'https://api.venice.ai/api/v1';

const IMAGE_JUDGE_SYSTEM_PROMPT = `You are an impartial AI judge evaluating two AI-generated images. Your job is to determine which image is better based on:

1. **Prompt Adherence** - How well does it match what was requested?
2. **Visual Quality** - Is it sharp, well-composed, with good lighting?
3. **Creativity** - Is it interesting and well-executed artistically?
4. **Technical Skill** - No artifacts, distortions, or obvious AI errors?

You MUST respond in this exact JSON format:
{
  "winner": "A" or "B",
  "reasoning": "Brief explanation (2-3 sentences) of why this image won",
  "scores": {
    "A": { "adherence": 1-10, "quality": 1-10, "creativity": 1-10, "technical": 1-10 },
    "B": { "adherence": 1-10, "quality": 1-10, "creativity": 1-10, "technical": 1-10 }
  }
}

Be decisive. One image must win. No ties.`;

export async function POST(request: NextRequest) {
  try {
    const { judgeModel, prompt, imageUrlA, imageUrlB, modelA, modelB } = await request.json();

    if (!judgeModel || !prompt || !imageUrlA || !imageUrlB) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    const apiKey = process.env.VENICE_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: 'Venice API key not configured' },
        { status: 500 }
      );
    }

    // Use the specified judge model (should be vision-capable)
    const visionModel = judgeModel;
    
    // Build request body with potential model-specific parameters
    const requestBody: Record<string, unknown> = {
      model: visionModel,
      messages: [],
      max_tokens: 1024,
      temperature: 0.3,
    };

    // Claude models need thinking disabled
    const modelLower = visionModel.toLowerCase();
    if (modelLower.includes('claude') && (modelLower.includes('sonnet') || modelLower.includes('opus'))) {
      requestBody.venice_parameters = {
        enable_thinking: false
      };
    }
    
    const userContent = [
      {
        type: 'text',
        text: `## Original Prompt
"${prompt}"

## Your Task
Compare Image A and Image B. Both were generated from the prompt above.
- Image A was generated by ${modelA || 'Model A'}
- Image B was generated by ${modelB || 'Model B'}

Evaluate both images and declare a winner. Respond with JSON only.`
      },
      {
        type: 'text',
        text: '## Image A:'
      },
      {
        type: 'image_url',
        image_url: { url: imageUrlA }
      },
      {
        type: 'text',
        text: '## Image B:'
      },
      {
        type: 'image_url',
        image_url: { url: imageUrlB }
      }
    ];

    // Complete the request body with messages
    requestBody.messages = [
      { role: 'system', content: IMAGE_JUDGE_SYSTEM_PROMPT },
      { role: 'user', content: userContent }
    ];

    const response = await fetch(`${VENICE_API_BASE}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error(`Venice API error for image judge:`, errorText);
      return NextResponse.json(
        { error: `Image judge API error: ${response.status}` },
        { status: response.status }
      );
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content || '';

    // Try to parse the JSON response
    try {
      const jsonMatch = content.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const verdict = JSON.parse(jsonMatch[0]);
        return NextResponse.json({
          winner: verdict.winner,
          reasoning: verdict.reasoning,
          scores: verdict.scores,
          judgeModel: visionModel,
        });
      } else {
        // Fallback
        const mentionsA = (content.match(/image\s*a/gi) || []).length;
        const mentionsB = (content.match(/image\s*b/gi) || []).length;
        return NextResponse.json({
          winner: mentionsA > mentionsB ? 'A' : 'B',
          reasoning: content.slice(0, 500),
          scores: null,
          judgeModel: visionModel,
        });
      }
    } catch {
      return NextResponse.json({
        winner: 'A',
        reasoning: content.slice(0, 500),
        scores: null,
        judgeModel: visionModel,
      });
    }
  } catch (error) {
    console.error('Image judge API error:', error);
    return NextResponse.json(
      { error: 'Failed to get image judgment' },
      { status: 500 }
    );
  }
}
